import fs from 'node:fs/promises';
import { describe, expect, it } from 'vitest';
import {
  NigmaAdapterPolicySchema,
  NigmaInvocationEnvelopeSchema,
  nigmaInvocationDigest,
  validateAndMapNigmaSubmission,
} from '../src/runtime/nigma_handoff';

describe('Nigma Python interoperability fixture', () => {
  it('accepts the exact F4.3 envelope and policy generated by Nigma', async () => {
    const fixture = JSON.parse(await fs.readFile(
      new URL('./fixtures/nigma-handoff-v1.json', import.meta.url), 'utf8',
    )) as Record<string, unknown>;
    expect(fixture.generator).toBe('Nigma/scripts/generate_ego_handoff_fixture.py');
    const invocation = NigmaInvocationEnvelopeSchema.parse(fixture.invocation);
    const policy = NigmaAdapterPolicySchema.parse(fixture.ego_policy);

    expect(nigmaInvocationDigest(invocation)).toBe(invocation.digest);
    const mapped = validateAndMapNigmaSubmission({
      invocation,
      learner_context: {
        user_id: 'fixture_learner',
        session_id: 'fixture_session',
        objective_id: 'fixture_objective',
      },
    }, policy, new Date(Date.parse(invocation.created_at) + 30_000));
    expect(mapped).toMatchObject({
      request_id: invocation.id,
      message: invocation.objective,
      capabilities: ['artifacts', 'documents.text', 'education.study_plan'],
      metadata: {
        nigma: {
          invocation_digest: invocation.digest,
          agent_route_id: invocation.agent_route.agent_route_id,
        },
      },
    });
  });
});
